package park.ui;

import park.service.ParkService; import park.util.*; import park.model.Employee;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*;

public class EmployeesPanel extends JPanel {
    private final ParkService service; private final Runnable refresh; private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Name","Role","Salary","Shift","Active"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable table=new JTable(model);
    public EmployeesPanel(ParkService s,Runnable r){service=s;refresh=r;setLayout(new BorderLayout(16,16));setBorder(BorderFactory.createEmptyBorder(12,2,2,2));setBackground(UiUtil.BG);JPanel head=new JPanel(new BorderLayout(12,10)); head.setOpaque(false); head.add(UiUtil.pageHeader("Employee Management","Manage park staff, roles, salaries and shift assignments."),BorderLayout.CENTER); head.add(UiUtil.infoStrip("STAFF SETUP","Add the employee name, role, salary and shift. Use this screen as the park staffing register.",UiUtil.PRIMARY),BorderLayout.SOUTH); add(head,BorderLayout.NORTH);UiUtil.styleTable(table);UiUtil.stripeTable(table);add(new JScrollPane(table),BorderLayout.CENTER);JPanel b=new JPanel(new FlowLayout(FlowLayout.LEFT,10,0));b.setOpaque(false);JButton add=UiUtil.actionButton("ADD EMPLOYEE  +",UiUtil.PURPLE,Color.WHITE);b.add(add);add(b,BorderLayout.SOUTH);add.addActionListener(e->dialog());refreshTable();}
    private void dialog(){JTextField n=new JTextField(),ph=new JTextField(),em=new JTextField(),role=new JTextField(),sal=new JTextField(),shift=new JTextField();JTextField[] fields={n,ph,em,role,sal,shift};for(JTextField f:fields)f.setPreferredSize(new Dimension(230,38));JPanel f=new JPanel(new GridLayout(0,2,10,10));String[] labels={"Name","Phone","Email","Role","Salary","Shift"};for(int i=0;i<labels.length;i++){f.add(new JLabel(labels[i]));f.add(fields[i]);}if(JOptionPane.showConfirmDialog(this,f,"Add Employee",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return;try{service.addEmployee(n.getText().trim(),ph.getText().trim(),em.getText().trim(),role.getText().trim(),NumberUtil.parseDouble(sal.getText(),"Salary"),shift.getText().trim());refresh.run();}catch(Exception ex){UiUtil.error(this,ex.getMessage());}}
    public void refreshTable(){model.setRowCount(0);for(Employee e:service.getEmployees())model.addRow(new Object[]{e.getId(),e.getName(),e.getRole(),String.format("$%.2f",e.getSalary()),e.getShift(),e.isActive()});UiUtil.styleTable(table);UiUtil.stripeTable(table);}
}
