package park.ui;

import park.model.*; import park.service.ParkService; import park.util.*;
import javax.swing.*; import java.awt.*;

public class FoodPanel extends JPanel {
    private final ParkService service; private final Runnable refresh; private final DefaultListModel<String> orders=new DefaultListModel<>(); private final JList<String> orderList=new JList<>(orders);
    public FoodPanel(ParkService s,Runnable r){service=s;refresh=r;setLayout(new BorderLayout(16,16));setBorder(BorderFactory.createEmptyBorder(12,2,2,2));setBackground(UiUtil.BG);JPanel head=new JPanel(new BorderLayout(12,10)); head.setOpaque(false); head.add(UiUtil.pageHeader("Food & Beverage","Take orders from park guests and monitor food sales."),BorderLayout.CENTER); head.add(UiUtil.infoStrip("ORDER FLOW","Pick an item from the menu → enter the customer name → enter quantity → the system calculates the total.",UiUtil.PURPLE),BorderLayout.SOUTH); add(head,BorderLayout.NORTH);JPanel menu=UiUtil.card();menu.setPreferredSize(new Dimension(440,0));menu.setLayout(new BorderLayout(10,10));JLabel h=new JLabel("Menu");h.setFont(new Font("SansSerif",Font.BOLD,18));menu.add(h,BorderLayout.NORTH);JPanel buttons=new JPanel();buttons.setOpaque(false);buttons.setLayout(new GridLayout(0,1,9,9));for(FoodItem item:service.getFoodItems()){JButton b=UiUtil.actionButton(item.getName()+"   •   $"+String.format("%.2f",item.getPrice()),new Color(245,243,255),UiUtil.PURPLE);b.setHorizontalAlignment(SwingConstants.LEFT);b.addActionListener(e->placeOrder(item));buttons.add(b);}menu.add(buttons,BorderLayout.CENTER);add(menu,BorderLayout.WEST);JPanel right=UiUtil.card();JLabel recent=new JLabel("Recent Orders");recent.setFont(new Font("SansSerif",Font.BOLD,18));right.add(recent,BorderLayout.NORTH);orderList.setFont(new Font("SansSerif",Font.PLAIN,15));orderList.setFixedCellHeight(42);orderList.setBackground(new Color(248,250,252));right.add(new JScrollPane(orderList),BorderLayout.CENTER);add(right,BorderLayout.CENTER);refreshOrders();}
    private void placeOrder(FoodItem item){String customer=JOptionPane.showInputDialog(this,"Customer name:","Walk-in");if(customer==null)return;String q=JOptionPane.showInputDialog(this,"Quantity:","1");if(q==null)return;try{FoodOrder o=service.createOrder(customer,item,NumberUtil.parseInt(q,"Quantity"));UiUtil.info(this,"Order "+o.getId()+" created. Total: $"+String.format("%.2f",o.getTotal()));refresh.run();}catch(Exception ex){UiUtil.error(this,ex.getMessage());}}
    public void refreshOrders(){orders.clear();service.getOrders().forEach(o->orders.addElement(o.getId()+"   •   "+o.getCustomer()+"   •   $"+String.format("%.2f",o.getTotal())));}
}
