package park.ui;

import park.model.*; import park.service.ParkService; import park.util.*;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*;

public class VisitorsPanel extends JPanel {
    private final ParkService service; private final Runnable refresh;
    private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Name","Age","Category","Phone","Email","Visits"},0){public boolean isCellEditable(int r,int c){return false;}};
    private final JTable table=new JTable(model);
    public VisitorsPanel(ParkService s,Runnable r){service=s;refresh=r;setLayout(new BorderLayout(16,16));setBorder(BorderFactory.createEmptyBorder(12,2,2,2));setBackground(UiUtil.BG);JPanel head=new JPanel(new BorderLayout(12,10)); head.setOpaque(false); head.add(UiUtil.pageHeader("Visitor Registry","Maintain a clean record of park guests and their visit history."),BorderLayout.CENTER); head.add(UiUtil.infoStrip("GETTING STARTED","Register each guest here first. Their visitor record gives the system a clean identity for admissions and reporting.",UiUtil.TEAL),BorderLayout.SOUTH); add(head,BorderLayout.NORTH);UiUtil.styleTable(table);UiUtil.stripeTable(table);add(new JScrollPane(table),BorderLayout.CENTER);JPanel bottom=new JPanel(new FlowLayout(FlowLayout.LEFT,10,0));bottom.setOpaque(false);JButton add=UiUtil.actionButton("REGISTER VISITOR  +",UiUtil.TEAL,Color.WHITE);JButton stats=UiUtil.actionButton("VIEW SUMMARY",UiUtil.PRIMARY,Color.WHITE);bottom.add(add);bottom.add(stats);add(bottom,BorderLayout.SOUTH);add.addActionListener(e->dialog());stats.addActionListener(e->UiUtil.info(this,"Total visitors: "+service.getVisitors().size()+"\nAdults: "+service.getVisitors().stream().filter(v->v.getAge()>=18).count()));refreshTable();}
    private void dialog(){JTextField n=new JTextField(),p=new JTextField(),em=new JTextField(),age=new JTextField();for(JTextField f:new JTextField[]{n,p,em,age})f.setPreferredSize(new Dimension(230,40));JPanel f=new JPanel(new GridLayout(0,2,10,10));f.add(new JLabel("Name"));f.add(n);f.add(new JLabel("Phone"));f.add(p);f.add(new JLabel("Email"));f.add(em);f.add(new JLabel("Age"));f.add(age);if(JOptionPane.showConfirmDialog(this,f,"Register Visitor",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return;try{if(n.getText().isBlank())throw new IllegalArgumentException("Name is required");service.registerVisitor(n.getText().trim(),p.getText().trim(),em.getText().trim(),NumberUtil.parseInt(age.getText(),"Age"));refresh.run();}catch(Exception ex){UiUtil.error(this,ex.getMessage());}}
    public void refreshTable(){model.setRowCount(0);service.getVisitors().forEach(v->model.addRow(new Object[]{v.getId(),v.getName(),v.getAge(),v.getCategory(),v.getPhone(),v.getEmail(),v.getVisits()}));UiUtil.styleTable(table);UiUtil.stripeTable(table);}
}
